repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.971
#    hooks:
#      - id: mypy
#        args: [--no-strict-optional, --ignore-missing-imports, ./app, ./tests]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

#  - repo: https://github.com/PyCQA/flake8
#    rev: 5.0.4
#    hooks:
#      - id: flake8
