[tool.aerich]
tortoise_orm = "app.core.tortoise.orm_config"
location = "./migrations"
src_folder = "./."

[tool.mypy]
# unfortunately cannot inject dependencies into super-linter
# so we have to ignore the imports as they will not have typehints
ignore_missing_imports = true

warn_unused_configs = true
disallow_any_generics = true
# disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
# disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = false
strict_equality = true

[tool.pytest.ini_options]
# cov=. -> coverage source is current directory. Note that --cov switch and pycharm debug dont work together
#           to enable pycharm test debug remove --cov. A better way is under Run/Debug Configuration ->
#           Templates -> Python tests -> pytest add the --no-cov to the Additional Arguments for all new tests
# cov-report term-missing:skip-covered -> report missing and skip those with 100% coverage
addopts =" --cov=. --cov-report=term-missing:skip-covered  --cov-fail-under=75 --verbose"
# to find your tests
python_files = ["tests.py", "test_*.py", "*_tests.py"]
# env files to load
env_files = [".env", ".test.env"]