-- upgrade --
ALTER TABLE "address" ALTER COLUMN "label" TYPE VARCHAR(25) USING "label"::VARCHAR(25);
ALTER TABLE "email" ALTER COLUMN "label" TYPE VARCHAR(25) USING "label"::VARCHAR(25);
ALTER TABLE "phone" ALTER COLUMN "label" TYPE VARCHAR(25) USING "label"::VARCHAR(25);
ALTER TABLE "significantdate" ALTER COLUMN "label" TYPE VARCHAR(25) USING "label"::VARCHAR(25);
-- downgrade --
ALTER TABLE "email" ALTER COLUMN "label" TYPE VARCHAR(15) USING "label"::VARCHAR(15);
ALTER TABLE "phone" ALTER COLUMN "label" TYPE VARCHAR(15) USING "label"::VARCHAR(15);
ALTER TABLE "address" ALTER COLUMN "label" TYPE VARCHAR(15) USING "label"::VARCHAR(15);
ALTER TABLE "significantdate" ALTER COLUMN "label" TYPE VARCHAR(15) USING "label"::VARCHAR(15);
